// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJbBORsVcd6w6Eey6MR0HIw1A5Zt_u1mc',
    appId: '1:19854769715:web:452bce783d11d408d3ad46',
    messagingSenderId: '19854769715',
    projectId: 'chatting-app-b548d',
    authDomain: 'chatting-app-b548d.firebaseapp.com',
    storageBucket: 'chatting-app-b548d.appspot.com',
    measurementId: 'G-B3LJEEDZY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIrEM7VSecMwEGhT0S1BYhcH4VcQmJ-MU',
    appId: '1:19854769715:android:4656f2b678de173cd3ad46',
    messagingSenderId: '19854769715',
    projectId: 'chatting-app-b548d',
    storageBucket: 'chatting-app-b548d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP2TSK2szrT3HItbyK3NVGKWoazxFeYgo',
    appId: '1:19854769715:ios:19217ef757eccbe5d3ad46',
    messagingSenderId: '19854769715',
    projectId: 'chatting-app-b548d',
    storageBucket: 'chatting-app-b548d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP2TSK2szrT3HItbyK3NVGKWoazxFeYgo',
    appId: '1:19854769715:ios:19217ef757eccbe5d3ad46',
    messagingSenderId: '19854769715',
    projectId: 'chatting-app-b548d',
    storageBucket: 'chatting-app-b548d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJbBORsVcd6w6Eey6MR0HIw1A5Zt_u1mc',
    appId: '1:19854769715:web:16b6de1def88114ed3ad46',
    messagingSenderId: '19854769715',
    projectId: 'chatting-app-b548d',
    authDomain: 'chatting-app-b548d.firebaseapp.com',
    storageBucket: 'chatting-app-b548d.appspot.com',
    measurementId: 'G-62NETXB3F7',
  );

}